application: uda-cs253-demo
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
#- url: /(.*\.css)
#  mime_type: text/css
#  static_files: css/\1
#  upload: /css/(.*\.css)

#- url: /(.*\.(bmp|gif|ico|jpeg|jpg|png))
#  static_files: img/\1
#  upload: /img/(.*\.(bmp|gif|ico|jpeg|jpg|png))

#- url: /(.*\.js)
#  mime_type: text/javascript
#  static_files: js/\1
#  upload: /js/(.*\.js)

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /img
  static_dir: img

- url: /
  script: main.app

- url: /sqltools
  script: sqltools.app

- url: /.*
  script: unit2.app

- url: /unit2/.*
  script: unit2.app

